subugoe_emo_item:
    path:      "gfl/{id}/latest/item.json"
    methods:  "GET"
    defaults: { _controller: SubugoeEMOBundle:Presentation:item }
subugoe_emo_manifest:
    path:      "gfl/{id}/manifest.json"
    methods:  "GET"
    defaults: { _controller: SubugoeEMOBundle:Presentation:manifest }

