subugoe_tido_page_annotation_collection:
    path:      "gfl/{id}/{page}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::pageAnnotationCollection }

subugoe_tido_annotation_collection:
    path:      "gfl/{id}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::annotationCollection }

subugoe_tido_annotation_page:
    path:      "gfl/{id}/{page}/annotationPage.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::annotationPage }

subugoe_tido_item_page:
    path:      "gfl/{idAndFoliant}/{revision}/item.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::item, "revision":"latest" }

subugoe_tido_item_full:
    path:      "gfl/{id}/{revision}/full.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::full, "revision":"0.0.2" }

subugoe_tido_manifest:
    path:      "gfl/{id}/manifest.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::manifest }

subugoe_tido_content:
    path:      "gfl/{id}/content"
    methods:  "GET"
    defaults: { _controller: Subugoe\EMOBundle\Controller\PresentationController::content }
